In [1]:
import numpy as np 
A = np.arange(0,9).reshape((3, 3))
B = np.ones((3, 3))
print(A,'\n\n', B)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2]:
# diagonal sum
print(np.einsum('ii', A))

12


In [3]:
# values on diagonals
print(np.einsum('ii->i', A))   

[0 4 8]


In [4]:
# sum on axis
print(np.einsum('ij->i', A))
print(np.einsum('ij->j', A))
A

[ 3 12 21]
[ 9 12 15]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# elipsis?
print(np.einsum('...j->...', A))
print(np.einsum('i...->...', A))
A

[ 3 12 21]
[ 9 12 15]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# transposition
print(np.einsum('ji', A))
A

[[0 3 6]
 [1 4 7]
 [2 5 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# transposition
print(np.einsum('ij, ji', A, A))
A

180


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])