In [12]:
import numpy as np 
A = np.arange(0,9).reshape((3, 3))
B = np.ones((3, 3))
print(A,'\n\n', B)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# diagonal sum
print(np.einsum('ii', A))

12


In [14]:
# values on diagonals
print(np.einsum('ii->i', A))   

[0 4 8]


In [15]:
# sum on axis
print(np.einsum('ij->i', A))
print(np.einsum('ij->j', A))
A

[ 3 12 21]
[ 9 12 15]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# elipsis?
print(np.einsum('...j->...', A))
print(np.einsum('i...->...', A))
A

[ 3 12 21]
[ 9 12 15]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# transposition
print(np.einsum('ji', A))
A

[[0 3 6]
 [1 4 7]
 [2 5 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
# transposition
print(np.einsum('ij, ji', A, A))
A

180


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
import numpy as np 
A = np.arange(0,9).reshape((3, 3))
B = np.arange(4,10).reshape((3, -1))
V = np.arange(1, 3)
A, B, V

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[4, 5],
        [6, 7],
        [8, 9]]),
 array([1, 2]))

In [28]:
np.einsum('ij, jk -> ik', A, B)

array([[ 22,  25],
       [ 76,  88],
       [130, 151]])

In [29]:
np.einsum('ij, ij -> ij', A, A)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [30]:
np.einsum('ij, ij -> ', A, A)

204

In [32]:
a = 10

assert a ==10